# Generated by Django 4.0.3 on 2022-06-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0002_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='description',
            field=models.TextField(default=2, verbose_name='About an Actor'),
            preserve_default=False,
        ),
    ]
