# Generated by Django 4.0.3 on 2022-06-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0003_actor_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default=2, verbose_name='Text'),
            preserve_default=False,
        ),
    ]
