# Generated by Django 4.0.3 on 2022-06-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0005_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(null=True, verbose_name='Comment'),
        ),
    ]
