# Generated by Django 4.0.3 on 2022-06-21 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0007_comment_slug_alter_comment_text_like_dislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
        migrations.AddField(
            model_name='dislike',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='netflix.movie'),
        ),
        migrations.AddField(
            model_name='like',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='netflix.movie'),
        ),
    ]
