# Generated by Django 4.0.3 on 2022-06-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0008_remove_comment_slug_remove_dislike_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='box_office',
            field=models.CharField(blank=True, default='1.50 billion', max_length=255, verbose_name='Box Office'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.CharField(blank=True, default='20 million', max_length=255, verbose_name='Budget'),
        ),
    ]
