# Generated by Django 4.0.3 on 2022-06-22 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0010_question_secondchoice_firstchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Poll Question')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.actor')),
            ],
        ),
        migrations.AlterField(
            model_name='firstchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.poll'),
        ),
        migrations.AlterField(
            model_name='secondchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.poll'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
