# Generated by Django 4.0.3 on 2022-06-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0012_alter_firstchoice_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstchoice',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='secondchoice',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
