# Generated by Django 4.0.3 on 2022-06-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0014_remove_firstchoice_title_remove_secondchoice_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='description',
            field=models.TextField(blank=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='director',
            name='description',
            field=models.TextField(blank=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='description',
            field=models.TextField(verbose_name='About'),
        ),
    ]
