# Generated by Django 4.0.3 on 2022-06-23 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0015_composer_description_director_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composer',
            options={'verbose_name': 'Composer', 'verbose_name_plural': 'Composers'},
        ),
    ]
