# Generated by Django 4.0.3 on 2022-06-23 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0016_alter_composer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.movie')),
            ],
        ),
    ]
