# Generated by Django 4.0.3 on 2022-06-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0017_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AddField(
            model_name='role',
            name='role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Actor Role'),
        ),
    ]
