# Generated by Django 4.0.3 on 2022-06-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0018_alter_role_options_role_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(blank=True, to='netflix.director', verbose_name='Director'),
        ),
    ]
