# Generated by Django 4.0.3 on 2022-06-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0019_remove_movie_director_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='type',
            field=models.CharField(default='Actor', max_length=255, verbose_name='Type'),
        ),
    ]
