# Generated by Django 4.0.3 on 2022-06-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0022_poll_composer_poll_director_alter_poll_actor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='actor',
        ),
        migrations.AddField(
            model_name='poll',
            name='actor',
            field=models.ManyToManyField(blank=True, to='netflix.actor'),
        ),
        migrations.RemoveField(
            model_name='poll',
            name='composer',
        ),
        migrations.AddField(
            model_name='poll',
            name='composer',
            field=models.ManyToManyField(blank=True, to='netflix.composer'),
        ),
        migrations.RemoveField(
            model_name='poll',
            name='director',
        ),
        migrations.AddField(
            model_name='poll',
            name='director',
            field=models.ManyToManyField(blank=True, to='netflix.director'),
        ),
    ]
