# Generated by Django 4.0.3 on 2022-06-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0023_remove_poll_actor_poll_actor_remove_poll_composer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(max_length=255, verbose_name='Poll Question'),
        ),
    ]
