# Generated by Django 4.0.3 on 2022-06-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0024_alter_poll_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='actor',
            field=models.ManyToManyField(to='netflix.actor', verbose_name='Actors'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='composer',
            field=models.ManyToManyField(to='netflix.composer', verbose_name='Composers'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='director',
            field=models.ManyToManyField(to='netflix.director', verbose_name='Directors'),
        ),
    ]
