# Generated by Django 4.0.3 on 2022-06-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0025_alter_poll_actor_alter_poll_composer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='firstchoice_title',
            field=models.CharField(default='Yes', max_length=255, verbose_name='First Choice Title'),
        ),
    ]
