# Generated by Django 4.0.3 on 2022-06-24 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0026_alter_poll_firstchoice_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstchoice',
            name='composer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='netflix.composer'),
        ),
        migrations.AddField(
            model_name='firstchoice',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='netflix.director'),
        ),
        migrations.AddField(
            model_name='secondchoice',
            name='composer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='netflix.composer'),
        ),
        migrations.AddField(
            model_name='secondchoice',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='netflix.director'),
        ),
    ]
