# Generated by Django 4.0.3 on 2022-06-24 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0027_firstchoice_composer_firstchoice_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstchoice',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='netflix.actor'),
        ),
        migrations.AlterField(
            model_name='secondchoice',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='netflix.actor'),
        ),
    ]
