# Generated by Django 4.0.3 on 2022-06-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0028_alter_firstchoice_actor_alter_secondchoice_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='actor',
            field=models.ManyToManyField(blank=True, to='netflix.actor', verbose_name='Actors'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='composer',
            field=models.ManyToManyField(blank=True, to='netflix.composer', verbose_name='Composers'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='director',
            field=models.ManyToManyField(blank=True, to='netflix.director', verbose_name='Directors'),
        ),
    ]
