# Generated by Django 4.0.3 on 2022-07-04 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0030_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='netflix.genre'),
        ),
    ]
