# Generated by Django 4.0.3 on 2022-07-04 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0031_view_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='netflix.movie'),
        ),
    ]
