# Generated by Django 4.0.3 on 2022-07-04 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0032_alter_view_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='view',
            name='genre',
        ),
    ]
