# Generated by Django 4.0.3 on 2022-07-12 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('netflix', '0035_alter_uservisit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_visit',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Visit'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='choice_total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstchoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.firstchoice')),
                ('secondchoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.secondchoice')),
            ],
        ),
    ]
