# Generated by Django 4.0.3 on 2022-07-12 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0036_profile_last_visit_alter_uservisit_user_choice_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='dislike',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='netflix.comment'),
        ),
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='netflix.comment'),
        ),
    ]
