# Generated by Django 4.0.3 on 2022-07-12 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0037_dislike_comment_like_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislike',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
    ]
