# Generated by Django 4.0.3 on 2022-07-13 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0039_commentlike_commentdislike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='choice_total',
        ),
    ]
