# Generated by Django 4.0.3 on 2022-07-14 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0041_white_dark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='white',
            name='user',
        ),
        migrations.DeleteModel(
            name='Dark',
        ),
        migrations.DeleteModel(
            name='White',
        ),
    ]
